[project]
id = "provider"
version = "0.0.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[link.provider]
source = "local"
path = "{project.out}/obj/provider/provider.o"
os = ["linux"]
isa = ["*"]
abi = ["*"]
export = true

[step.provider]
cmd = "sh build.sh {project.out}/obj/provider/provider.o"
in = ["build.sh", "provider.c"]
out = ["{project.out}/obj/provider/provider.o"]
need = []
