[project]
id = "pe-resource-native"
version = "3.4.5"
src = "src"
out = "out"

[target.windows]
isa = "x86_64"
os = "windows"
abi = "win64"

[profile.debug]
opt = 0
debug = false
simd = "scalarize"

[profile.release]
opt = 2
debug = false
simd = "scalarize"

[artifact.game-app]
kind = "bin"
entry = "main.mach"
out = "bin/game-app.exe"
targets = ["*"]
link = ["kernel32"]
icon = "assets/app.ico"
manifest = "assets/app.manifest"

[link.kernel32]
source = "system"
name = "kernel32.dll"
os = ["windows"]
isa = ["*"]
abi = ["*"]
export = false

[dep.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
