[project]
name = "std"
version = "0.1.0"
target-name = "std"
default-target = "native"

[directories]
src-dir = "src"
dep-dir = "dep"
lib-dir = "lib"
out-dir = "out"

[targets.native]
target = "x86_64-pc-linux-gnu"
opt-level = 2
build-library = true
emit-object = true
emit-ast = false
emit-ir = false
emit-asm = false

[runtime]
runtime = "std.runtime"

[modules]
std = "std"
