[project]
name = "mach"
version = "0.0.1"
entrypoint = "main.mach"

[directories]
src-dir = "src"
dep-dir = "dep"
out-dir = "out"

# declare std as a dependency via relative path
[deps]
std = { path = "../mach-std", src = "src" }

# map short alias to dep.std for nicer imports
[modules]
std = "dep.std"

[runtime]
runtime = "std.runtime"
