[project]
id      = "case"
name    = "case"
version = "0.0.0"
src     = "src"
target  = "freestanding-riscv64"
out     = "out/{target}/{profile}/bin/{name}{ext}"

[target.freestanding-riscv64]
isa = "riscv64"
os  = "freestanding"
abi = "lp64"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[bin.case]
entry = "main.mach"
