[project]
id = "prov"
version = "0.0.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[link.kernel32]
source = "system"
name = "kernel32.dll"
library = "kernel32"
symbols = ["Sleep"]
os = ["windows"]
isa = ["*"]
abi = ["*"]
export = true
