[project]
id      = "case"
name    = "case"
version = "0.0.0"
src     = "src"
dep     = "dep"
target  = "darwin-aarch64"
out     = "out/{target}/{profile}/bin/{name}{ext}"

[target.darwin-aarch64]
isa = "aarch64"
os  = "darwin"
abi = "aapcs64"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[bin.case]
entry = "main.mach"

[deps.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
