[project]
id = "case"
version = "1.0.0"
src = "src"
out = "out"

[target.linux]
isa = "x86_64"
os = "linux"
abi = "sysv64"

[profile.debug]
opt = 0
debug = false
simd = "scalarize"

[artifact.case]
kind = "bin"
entry = "main.mach"
out = "bin/case"
targets = ["*"]
link = []
need = []

