[project]
id      = "case"
name    = "case"
version = "0.0.0"
src     = "src"
target  = "freestanding-x86_64"
out     = "out/{target}/{profile}/bin/{name}{ext}"

[target.freestanding-x86_64]
isa = "x86_64"
os  = "freestanding"
abi = "sysv64"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[bin.case]
entry = "main.mach"
