[project]
id = "case"
version = "0.0.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.darwin-aarch64]
isa = "aarch64"
os  = "darwin"
abi = "aapcs64"

[profile.debug]
opt = 0
debug = false
simd = "scalarize"

[profile.release]
opt = 2
debug = false
simd = "scalarize"

[artifact.case]
kind = "bin"
entry = "main.mach"
out = "bin/case"
targets = ["*"]
link = ["System", "objc", "cxx", "iconv", "z", "xml2", "bz2", "curses"]
need = []

[link.System]
source = "system"
name = "/usr/lib/libSystem.B.dylib"
library = "System"
symbols = []
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false

[link.objc]
source = "system"
name = "/usr/lib/libobjc.A.dylib"
library = "objc"
symbols = []
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false

[link.cxx]
source = "system"
name = "/usr/lib/libc++.1.dylib"
library = "cxx"
symbols = []
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false

[link.iconv]
source = "system"
name = "/usr/lib/libiconv.2.dylib"
library = "iconv"
symbols = []
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false

[link.z]
source = "system"
name = "/usr/lib/libz.1.dylib"
library = "z"
symbols = []
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false

[link.xml2]
source = "system"
name = "/usr/lib/libxml2.2.dylib"
library = "xml2"
symbols = []
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false

[link.bz2]
source = "system"
name = "/usr/lib/libbz2.1.0.dylib"
library = "bz2"
symbols = []
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false

[link.curses]
source = "system"
name = "/usr/lib/libcurses.dylib"
library = "curses"
symbols = []
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false
