#!/usr/bin/env bash
# update-deps.sh — regenerate int/deps.lock, the pin source for deps only int builds.
#
# usage: update-deps.sh <compiler>
#
# Run it when a case adds a git dep the root manifest does not declare, or to move
# the int-only pins onto their refs' current tips. check-deps.sh names the condition
# on the PR that introduces it, so this is never something to discover by running
# the suite (#2729).
#
# Deps the ROOT manifest declares are not touched: mach.lock already records them,
# it is authoritative for them, and bumping the compiler's dependency is meant to
# bump int's in the same commit. Recording them here too would give one dep two
# places to bump, so check-deps.sh fails if this file ever does.
#
# Resolution is the compiler's job, never this script's. It builds a scratch project
# declaring exactly the int-only deps and runs `<compiler> dep pull` in it, then
# copies the lock that produced. Nothing here maps a ref to a commit, so there is no
# second implementation to drift from `mach dep`'s - and because the scratch pull is
# transitive, a dep-of-a-dep lands in the lock the same way it lands in the root's.
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$here/deps.sh"

compiler=${1:-}
[ -n "$compiler" ] || { echo "usage: update-deps.sh <compiler>" >&2; exit 2; }
case "$compiler" in
    /*) : ;;
    *)  compiler=$(CDPATH= cd -- "$(dirname -- "$compiler")" && pwd)/$(basename -- "$compiler") ;;
esac
[ -x "$compiler" ] || { echo "update-deps.sh: '$compiler' is not executable" >&2; exit 2; }

scratch=$(mktemp -d)
trap 'rm -rf "$scratch"' EXIT

{
    echo '[project]'
    echo 'id = "int-deps"'
    echo 'version = "0.0.0"'
    echo 'src = "src"'
} >"$scratch/mach.toml"

wanted=
while read -r name url ref case_id; do
    [ -n "$name" ] || continue
    # the root lock owns anything the compiler also builds against.
    [ -z "$(lock_commit "$root_lock" "$name")" ] || continue
    case " $wanted " in *" $name "*) continue ;; esac
    wanted="$wanted $name"
    printf '\n[dep.%s]\ngit = "%s"\nref = "%s"\n' "$name" "$url" "$ref" >>"$scratch/mach.toml"
    echo "resolving $name ($ref) declared by $case_id"
done <<EOF
$(int_git_deps)
EOF

if [ -z "$wanted" ]; then
    rm -f "$int_lock"
    echo "update-deps: no int-only git deps; removed int/deps.lock"
    exit 0
fi

(cd "$scratch" && "$compiler" dep pull) >"$scratch/pull.log" 2>&1 || {
    echo "update-deps.sh: dep pull failed" >&2
    sed 's/^/    /' "$scratch/pull.log" >&2
    exit 1
}

[ -f "$scratch/mach.lock" ] || {
    echo "update-deps.sh: dep pull wrote no mach.lock" >&2
    exit 1
}

{
    echo "# int/deps.lock — the pin source for git deps only the int suite builds."
    echo "#"
    echo "# generated by int/lib/update-deps.sh; do not edit by hand. deps the ROOT"
    echo "# manifest declares are NOT here: the root mach.lock is authoritative for"
    echo "# those, so they have exactly one place to bump (int/lib/deps.sh)."
    grep -v '^#' "$scratch/mach.lock"
} >"$int_lock"

echo "update-deps: wrote ${int_lock##*/} for$wanted"
bash "$here/check-deps.sh"
