[project]
id = "case"
version = "0.0.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.freestanding-aarch64]
isa = "aarch64"
os  = "freestanding"
abi = "aapcs64"

[profile.debug]
opt = 0
debug = false

[profile.release]
opt = 2
debug = false

[artifact.case]
kind = "bin"
entry = "main.mach"
out = "bin/case"
targets = ["*"]
link = []
need = []
