[project]
id = "case"
version = "0.0.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.darwin-x86_64]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[profile.debug]
opt = 0
debug = false
simd = "scalarize"

[profile.release]
opt = 2
debug = false
simd = "scalarize"

[artifact.case]
kind = "bin"
entry = "main.mach"
out = "bin/case"
targets = ["*"]
link = ["System", "curses"]
need = []

[link.System]
source = "system"
name = "/usr/lib/libSystem.B.dylib"
library = "System"
symbols = ["Sleep"]
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false

[link.curses]
source = "system"
name = "/usr/lib/libcurses.dylib"
library = "curses"
symbols = ["Beep"]
os = ["darwin"]
isa = ["*"]
abi = ["*"]
export = false
