[project]
id = "resource-missing"
version = "1.0.0"
src = "src"
out = "out"

[target.windows]
isa = "x86_64"
os = "windows"
abi = "win64"

[profile.debug]
opt = 0
debug = false
simd = "scalarize"

[artifact.resource-missing]
kind = "bin"
entry = "main.mach"
out = "bin/resource-missing"
targets = ["*"]
link = ["kernel32"]
need = []
icon = "assets/does-not-exist.ico"

[link.kernel32]
source = "system"
name = "kernel32.dll"
os = ["windows"]
isa = ["*"]
abi = ["*"]
export = false
