[project]
id      = "case"
name    = "case"
version = "0.0.0"
src     = "src"
target  = "windows"
out     = "out/{target}/{profile}/bin/{name}{ext}"

[target.windows]
isa = "x86_64"
os  = "windows"
abi = "win64"
ext = ".exe"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[os.windows]
libs = ["kernel32.dll"]

[bin.case]
entry = "main.mach"
