[project]
id      = "case"
name    = "case"
version = "0.0.0"
src     = "src"
dep     = "dep"
target  = "linux"
out     = "out/{target}/{profile}/bin/{name}{ext}"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[profile.debug]
opt = 0

[profile.release]
opt = 2

[bin.case]
entry = "main.mach"

[deps.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
