[project]
id = "resource-gate"
version = "1.0.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux]
isa = "x86_64"
os = "linux"
abi = "sysv64"

[profile.debug]
opt = 0
debug = false
simd = "scalarize"

[profile.release]
opt = 2
debug = false
simd = "scalarize"

[artifact.resource-gate]
kind = "bin"
entry = "main.mach"
out = "bin/resource-gate"
targets = ["*"]
link = []
need = []
icon = "missing/app.ico"
manifest = "missing/app.manifest"

[dep.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
